package com.borderrun.app.data.local.entity

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * Room entity representing a generated daily challenge.
 *
 * Challenges are generated by [ContentSyncWorker] each day. [sessionId] is
 * populated when the user completes the challenge.
 *
 * @property id Auto-generated primary key.
 * @property title Human-readable challenge name, e.g. `"Island Nations"`.
 * @property description Short description shown on the home card.
 * @property region Optional region filter; `null` for mixed-region challenges.
 * @property theme Machine-readable theme key, e.g. `"island"`, `"landlocked"`, `"starting_letter"`.
 * @property date Unix timestamp (ms) at midnight (UTC) for the challenge's day.
 * @property completed Whether the user has finished this challenge.
 * @property sessionId Foreign key → [QuizSessionEntity.id] once completed; `null` otherwise.
 */
@Entity(
    tableName = "daily_challenges",
    foreignKeys = [
        ForeignKey(
            entity = QuizSessionEntity::class,
            parentColumns = ["id"],
            childColumns = ["sessionId"],
            onDelete = ForeignKey.SET_NULL,
        ),
    ],
    indices = [Index("sessionId")],
)
data class DailyChallengeEntity(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val title: String,
    val description: String,
    val region: String?,
    val theme: String,
    val date: Long,
    val completed: Boolean = false,
    val sessionId: Int? = null,
)
