package com.borderrun.app.data.local.dao

import androidx.room.Dao
import androidx.room.Insert
import androidx.room.Query
import androidx.room.Upsert
import com.borderrun.app.data.local.entity.DailyChallengeEntity
import kotlinx.coroutines.flow.Flow

/**
 * Data Access Object for the `daily_challenges` table.
 */
@Dao
interface DailyChallengeDao {

    /**
     * Inserts a new [DailyChallengeEntity] generated by [ContentSyncWorker].
     *
     * @param challenge The challenge to insert.
     * @return The auto-generated primary key for the new row.
     */
    @Insert
    suspend fun insertChallenge(challenge: DailyChallengeEntity): Long

    /**
     * Upserts an existing challenge — used to mark it completed and link
     * its [DailyChallengeEntity.sessionId].
     *
     * @param challenge The updated challenge entity.
     */
    @Upsert
    suspend fun upsertChallenge(challenge: DailyChallengeEntity)

    /**
     * Returns the challenge for today as a reactive [Flow].
     *
     * [dayTimestamp] should be the Unix timestamp (ms) at midnight (UTC) for
     * today's date, matching how [ContentSyncWorker] stored it.
     *
     * @param dayTimestamp Midnight timestamp for today.
     * @return Flow emitting today's [DailyChallengeEntity] or `null` if not generated yet.
     */
    @Query("SELECT * FROM daily_challenges WHERE date = :dayTimestamp LIMIT 1")
    fun getTodaysChallenge(dayTimestamp: Long): Flow<DailyChallengeEntity?>

    /**
     * Returns all challenges in descending date order.
     *
     * @return Flow emitting the full history of daily challenges.
     */
    @Query("SELECT * FROM daily_challenges ORDER BY date DESC")
    fun getAllChallenges(): Flow<List<DailyChallengeEntity>>

    /**
     * Returns a challenge by its [id].
     *
     * @param id Primary key of the challenge.
     */
    @Query("SELECT * FROM daily_challenges WHERE id = :id")
    suspend fun getChallengeById(id: Int): DailyChallengeEntity?

    /**
     * Deletes all rows from the `daily_challenges` table.
     *
     * Called from "Clear All My Data" in Settings.
     */
    @Query("DELETE FROM daily_challenges")
    suspend fun deleteAll()
}
